```{r}

#CrimeRate - Per capita crime rate by city
#Indus - Proportion of non-retail business acres per city.
#River – River front or not (1-bounds river; 0-otherwise)
#AvgRoom - Average number of rooms per dwelling per city
#Age – Average age of a house by city
#Tax - full-value property-tax rate per $10,000
#PTRatio - pupil-teacher ratio by city
#LStat - % lower status of the population by city
#MedPrice - Median price of owner-occupied homes in $1000's

#Load necessary libraries
#------------------------
library(tidyverse)
library(ggplot2)
library(GGally)
library(leaps)
library(MASS)

#Ingest data
#------------------------
cincinnati <- read_csv("CINCINNATI.csv")
head(cincinnati)

```

```{r}
#Data cleaning
#------------------------

#Check for missing values
any(is.na(cincinnati))

#Check for duplicates
colSums(is.na(cincinnati))

#Check for correct format
str(cincinnati$CrimeRate)
str(cincinnati$Indus)
str(cincinnati$River)
str(cincinnati$AvgRoom)
str(cincinnati$Age)
str(cincinnati$Tax)
str(cincinnati$PTRatio)
str(cincinnati$LStat)
str(cincinnati$MedPrice)

#Check for inconsistencies/invalid values
any(cincinnati$CrimeRate < 0)
any(cincinnati$Indus <= 0)
any(cincinnati$River < 0 | cincinnati$River > 1)
any(cincinnati$AvgRoom < 0)
any(cincinnati$Age < 0)
any(cincinnati$Age <= 0)
any(cincinnati$Tax <= 0)
any(cincinnati$PTRatio <= 0)
any(cincinnati$PTRatio <= 0)
any(cincinnati$LStat < 0 | cincinnati$LStat > 100)
any(cincinnati$MedPrice <= 0)

#Look for outliers, determine how to handle them
summary(cincinnati$CrimeRate)
boxplot(cincinnati$CrimeRate, main = "Boxplot of Crime Rate")
hist(cincinnati$CrimeRate, breaks = 20, col = "lightcoral", main = "Histogram of Crime Rate")
#Conclusion: There are two high crimerate outliers, but they are still reasonable, and without knowing which city the crime rate is associated with, there's no way to investigate to see if we can justify removing it 

summary(cincinnati$Indus)
boxplot(cincinnati$Indus, main = "Boxplot of Porportion of Industry")
hist(cincinnati$Indus, breaks = 20, col = "lightcoral", main = "Histogram of Propotion of Industry")
#Conclusion: No outliers

summary(cincinnati$AvgRoom)
boxplot(cincinnati$AvgRoom, main = "Boxplot of Average Number of Rooms")
hist(cincinnati$AvgRoom, breaks = 20, col = "lightcoral", main = "Histogram of Average Number of Rooms")
#Conclusion: No outliers

summary(cincinnati$Age)
boxplot(cincinnati$Age, main = "Boxplot of Average Number of Rooms")
hist(cincinnati$Age, breaks = 20, col = "lightcoral", main = "Histogram of Average Number of Rooms")
#Conclusion: No outliers

summary(cincinnati$Tax)
boxplot(cincinnati$Tax, main = "Boxplot of Tax Rate")
hist(cincinnati$Tax, breaks = 20, col = "lightcoral", main = "Histogram of Tax Rate")
outlier <- subset(cincinnati, Tax == 666)
outlier
#Conclusion: Initially it looks like there is an outlier on 666, but upon further examination, there are 36 records with this value, meaning it's not an outlier

summary(cincinnati$PTRatio)
boxplot(cincinnati$PTRatio, main = "Boxplot of Pupil-teacher ratio")
hist(cincinnati$PTRatio, breaks = 20, col = "lightcoral", main = "Histogram of Pupil-teacher ratio")
#Conclusion: One entry is a bit low, but not an outlier

summary(cincinnati$LStat)
boxplot(cincinnati$LStat, main = "Boxplot of Lower Status Proportion")
hist(cincinnati$LStat, breaks = 20, col = "lightcoral", main = "Histogram of Lower Status Proportion")
#Conclusion: No outliers

summary(cincinnati$MedPrice)
boxplot(cincinnati$MedPrice, main = "Boxplot of Median House Price")
hist(cincinnati$MedPrice, breaks = 20, col = "lightcoral", main = "Histogram of Median House Price")
#Conclusion: No outliers
```

```{r}
#Exploratory Analysis
#------------------------
#Analyze relationship between variables
ggpairs(cincinnati)
#Biggest impact on Median Home Price:
#-AvgRooms 0.747 (More rooms = more $)
#-LStat -0.751 (Lower status = less $)
#-PTRatio -0.575 (higher ratio = less teachers/student = less $)
#-Indus -0.574 (more non-retail business = less appealing to live at = less $)
#-Tax -0.540 (higher tax rate = lower $)
#-Age -0.482 (the older the house = less $)

#Possible Variable interdependency
#-Tax/CrimeRate 0.538
#-Tax/Indus 0.698
#-Age/Indus 0.671
#-LStat/Indus 0.645
#-LStat/AvgRoom -0.615
#-Tax/Age  0.508
#-Age/LStat 0.654
#-LStat/Tax 0.565


#Check linear regression assumption of linearity
ggplot(cincinnati, aes(x = CrimeRate, y = MedPrice)) + 
  geom_point() +  
  labs(title = "Crimerate vs Price",
       x = "Crimerate",
       y = "Price") +
  theme_minimal()             
#Result: Negative non-linear

ggplot(cincinnati, aes(x = River, y = MedPrice)) + 
  geom_point() +  
  labs(title = "River vs Price",
       x = "River",
       y = "Price") +
  theme_minimal()             
#Result: Small negative correlation for on river

ggplot(cincinnati, aes(x = AvgRoom, y = MedPrice)) + 
  geom_point() +  
  labs(title = "AvgRoom vs Price",
       x = "AvgRoom",
       y = "Price") +
  theme_minimal()             
#Result: Clear Positive Linear 

ggplot(cincinnati, aes(x = Age, y = MedPrice)) + 
  geom_point() +  
  labs(title = "Age vs Price",
       x = "Age",
       y = "Price") +
  theme_minimal()             
#Result: Negative Non-linear 

ggplot(cincinnati, aes(x = Tax, y = MedPrice)) + 
  geom_point() +  
  labs(title = "Tax vs Price",
       x = "Tax",
       y = "Price") +
  theme_minimal()             
#Result: Negative Correlation

ggplot(cincinnati, aes(x = PTRatio, y = MedPrice)) + 
  geom_point() +  
  labs(title = "PTRatio vs Price",
       x = "PTRatio",
       y = "Price") +
  theme_minimal()             
#Result: Loose linear negative

ggplot(cincinnati, aes(x = LStat, y = MedPrice)) + 
  geom_point() +  
  labs(title = "LStat vs Price",
       x = "LStat",
       y = "Price") +
  theme_minimal()             
#Result: Non-linear negative

```


```{r}
#Question Investigation
#------------------------
# ==== examining distribution of crime rate ====

ggplot(cincinnati, aes(x=CrimeRate))+
  geom_histogram()

summary(cincinnati$CrimeRate)
 #    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 # 0.01096  0.07250  0.19160  3.34698  2.69719 88.97620 

# ==== recoding crimerate  ====

# breakpoints: (0, Q1, Q3, inf) -> low, medium, high
cincinnati$CrimeRate <- cut(
  cincinnati$CrimeRate,
  breaks = c(0, 0.07250, 2.69719, Inf),    # Define breakpoints for "low", "medium", "high"
  labels = c("low", "medium", "high")      # Labels for each category
)
ggpairs(cincinnati, aes(color=cincinnati$CrimeRate, alpha=0.5))



# ==== alt crimerate breakpoints ====

cincinnati <- read.csv("CINCINNATI.csv")
cincinnati$River <- recode(cincinnati$River, `0`="otherwise", `1`="bounds river")

# using (0, Q1, Q3, inf) as breakpoints for low, medium, high didn't seem to represent it well
# using arbitrary (0, 1, 5, inf) seems like better breakpoints

cincinnati$CrimeRate <- cut(
  cincinnati$CrimeRate,
  breaks = c(0, 1, 5, Inf),    # Define breakpoints for "low", "medium", "high"
  labels = c("low", "medium", "high")      # Labels for each category
)

ggpairs(cincinnati, aes(color=cincinnati$CrimeRate, alpha=0.5))

```


```{r}

# Investigating the RelationShip between Housing Age and Room Size
ggplot(cincinnati, aes(x = Age, y = AvgRoom)) +
  geom_point(color = "blue") +
  labs(title = "Relationship between Housing Age and Average Room Size",
       x = "Housing Age (Years)",
       y = "Average Number of Rooms") +
  theme_minimal()

# Calculate correlation coefficient
age_avgroom_cor <- cor(cincinnati$Age, cincinnati$AvgRoom)
print(paste("The Pearson correlation coefficient between Age and AvgRoom is:", round(age_avgroom_cor, 3)))

cor.test(cincinnati$Age, cincinnati$AvgRoom)

```

```
#Interpretation:
The correlation between the age and AvgRoom is -0.2423 , which means there is a mild
negative linear relationship between them and as house get older, they tend to have slightly fewer rooms on average.
Upon checking the p-value which is 0.002811 < 0.05 , we can say the observation is significantly significant.
Also the confidence interval doesnot contain zero, it supports that true correlation is different from zero 
and that there is a statistically significant negative relationship. 
We can conclude that, in our dataset, as the housing age increases, there is a 
slight tendency for the average number of rooms to decrease.

```

```{r}
#Investigating: Is there a relationship between the student-teacher ratio (PTRatio) and the crime rate (CrimeRate) in the city?
ggplot(cincinnati, aes(x = PTRatio, y = CrimeRate)) +
  geom_point(color = "blue") +
  labs(title = "Relationship between PTRatio and CrimeRate",
       x = "PTRatio",
       y = "CrimeRate") +
  theme_minimal()

# Calculate correlation coefficient
ptratio_crimerate_cor <- cor(cincinnati$PTRatio, cincinnati$CrimeRate)
print(paste("The Pearson correlation coefficient between PTRatio and CrimeRate is:", round(ptratio_crimerate_cor, 3)))

cor.test(cincinnati$PTRatio, cincinnati$CrimeRate)

```
```
##Interpretation:
The correlation between PTRatio and Crimerate is 0.274, which suggests that as the ratio of students to teachers increases, so does the crimerate. This intuitively makes sense, because less affuent cities will have less teachers for students, and areas such as this are typically more prone to crime. 
Upon checking the p-value which is 0.00067 < 0.05 , we can say the observation is significantly significant.
Also the confidence interval doesnot contain zero, it supports that true correlation is different from zero and that there is a statistically significant negative relationship. 
We can conclude that, in our dataset, as the housing age increases, there is a 
slight tendency for the average number of rooms to decrease.
```

```{r}
#Linear Regression
#------------------------
model <- lm(MedPrice ~ CrimeRate + Indus + River + AvgRoom + Age + Tax + PTRatio + LStat, data = cincinnati)
summary(model)

#Residual Analysis
plot(model$fitted.values, residuals(model),
     xlab = "Fitted Values", ylab = "Residuals",
     main = "Residuals vs Fitted Values")
abline(h = 0, col = "red")
#Results: It looks like there is some non-linearity here, varience looks ok.

#Check Normality
qqnorm(residuals(model), main = "Q–Q Plot of Model Residuals")
qqline(residuals(model), col = "red")
#Normality looks ok

model_log <- lm(log(MedPrice) ~ CrimeRate + Indus + River + AvgRoom + Age + Tax + PTRatio + LStat, data = cincinnati)
qqnorm(residuals(model_log), main = "Q–Q Plot of log(MedPrice) Model Residuals")
qqline(residuals(model_log), col = "red")
summary(model_log)

#BOXCOX
bc <- boxcox(model, plotit = TRUE)
lambda <- bc$x[which.max(bc$y)]
cat("Optimal lambda:", lambda, "\n")

lambda_opt <- 0.2626263
cincinnati1 <- cincinnati %>%
  mutate(MedPrice_trans = (MedPrice^lambda_opt - 1)/lambda_opt)

model_boxcox <- lm(MedPrice_trans ~ CrimeRate + Indus + River + AvgRoom + Age + Tax + PTRatio + LStat, data = cincinnati1)
summary(model_boxcox)

qqnorm(residuals(model_boxcox), main = "Q–Q Plot of Model Residuals")
qqline(residuals(model_boxcox), col = "red")

```

```{r}
#Best Subset Model Selection
best_subset_model <- regsubsets(MedPrice ~ ., data = cincinnati, nbest = 1)
best_subset_summary <- summary(best_subset_model)
#Add RSS, Adjusted R², Cp, and BIC to the same data frame
results <- data.frame(
  NumVar = 1:nrow(best_subset_summary$which),
  best_subset_summary$outmat,
  Rsq = best_subset_summary$rsq,
  RSS = best_subset_summary$rss,
  AdjR2 = best_subset_summary$adjr2,
  Cp = best_subset_summary$cp,
  BIC = best_subset_summary$bic
  )
print(results)


```
